#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

fail() {
  printf 'MoUI readiness check failed: %s\n' "$1" >&2
  exit 1
}

require_file() {
  local path="$1"
  [[ -f "$path" ]] || fail "missing file $path"
}

require_executable() {
  local path="$1"
  require_file "$path"
  [[ -x "$path" ]] || fail "$path is not executable"
}

require_text() {
  local path="$1"
  local text="$2"
  rg -q --fixed-strings -- "$text" "$path" ||
    fail "$path does not mention expected text: $text"
}

reject_text() {
  local path="$1"
  local text="$2"
  if rg -q --fixed-strings -- "$text" "$path"; then
    fail "$path contains forbidden text: $text"
  fi
}

require_ordered_text() {
  local path="$1"
  local first="$2"
  local second="$3"
  local output after_first
  output="$(cat "$path")"
  after_first="${output#*"$first"}"
  if [[ "$after_first" == "$output" || "$after_first" != *"$second"* ]]; then
    fail "$path does not contain expected order: $first before $second"
  fi
}

for path in \
  docs/moui-integration-smoke.md \
  docs/platform-gaps.md \
  docs/testing.md \
  README.mbt.md \
  examples/moui_macos_smoke/main.mbt \
  examples/moui_web_smoke/index.html \
  examples/moui_web_smoke/main.mbt \
  examples/moui_linux_smoke/main.mbt \
  examples/moui_linux_smoke/config_native.c \
  examples/moui_windows_smoke/main.mbt \
  examples/moui_windows_smoke/input_native.c \
  docs/ffi-linux-export-allowlist.txt \
  docs/ffi-windows-export-allowlist.txt \
  scripts/check_moui_macos_smoke.sh \
  scripts/check_moui_web_smoke.sh \
  scripts/check_moui_linux_smoke.sh \
  scripts/check_moui_windows_smoke.sh \
  scripts/record_moui_evidence.sh \
  scripts/capture_moui_runtime_evidence.sh \
  scripts/check_moui_runtime_log.sh \
  scripts/smoke_runtime.sh
do
  require_file "$path"
done

for path in \
  scripts/check_moui_macos_smoke.sh \
  scripts/check_moui_web_smoke.sh \
  scripts/check_moui_linux_smoke.sh \
  scripts/check_moui_windows_smoke.sh \
  scripts/record_moui_evidence.sh \
  scripts/capture_moui_runtime_evidence.sh \
  scripts/check_moui_runtime_log.sh \
  scripts/smoke_runtime.sh
do
  require_executable "$path"
done

require_text docs/platform-gaps.md "| macOS | Passed"
require_text docs/platform-gaps.md "| Web | Passed"
require_text docs/platform-gaps.md "| Linux | Pending matching Linux host"
require_text docs/platform-gaps.md "| Windows | Pending matching Windows host"
require_text docs/platform-gaps.md 'Treat `Pending` as missing evidence'
require_text docs/platform-gaps.md "MoUI-ready only after its build smoke and runtime smoke have both been observed"
reject_text docs/platform-gaps.md "| Linux | Passed"
reject_text docs/platform-gaps.md "| Windows | Passed"
reject_text linux/window.mbt "None => primary_monitor()"

require_text docs/moui-integration-smoke.md "Do not mark a backend runtime smoke as passed unless"
require_text docs/moui-integration-smoke.md "WINDOW_MOUI_LINUX_REQUIRE_INPUT=1"
require_text docs/moui-integration-smoke.md "Window::content_view_handle()"
require_text docs/moui-integration-smoke.md "Window::canvas_id()"
require_text docs/moui-integration-smoke.md "keyboard text or IME commit text"
require_text docs/moui-integration-smoke.md "monitor/current-monitor probes"
require_text docs/moui-integration-smoke.md "cursor state"
require_text docs/moui-integration-smoke.md "cursor Icon(Text)"
require_text docs/moui-integration-smoke.md "present_rgba_pixels"
require_text docs/moui-integration-smoke.md "Win32 keyboard, mouse, and IME delivery"
require_text docs/moui-integration-smoke.md "Destroyed"
require_text docs/moui-integration-smoke.md "bash scripts/record_moui_evidence.sh <backend>"
require_text docs/moui-integration-smoke.md "bash scripts/capture_moui_runtime_evidence.sh <linux|windows> --log"
require_text docs/moui-integration-smoke.md "scripts/check_moui_runtime_log.sh <linux|windows> <captured-log>"
require_text docs/moui-integration-smoke.md "Copyable recorder commands"
require_text docs/moui-integration-smoke.md "--host \"Linux Wayland/Weston CI\""
require_text docs/moui-integration-smoke.md "--host \"Windows Win32 CI\""
require_text docs/moui-integration-smoke.md "representative keyboard text a"
require_text docs/moui-integration-smoke.md "surface enter/current-output tracking"
require_text docs/moui-integration-smoke.md '`primary=true`'
require_text docs/moui-integration-smoke.md "IME probe enabled/update/disable"
require_text docs/moui-integration-smoke.md "public IME probe enable/update/disable"
require_text docs/moui-integration-smoke.md "HWND/HINSTANCE/raw_display/raw_window handle fields"
require_text docs/moui-integration-smoke.md "Window::rwh_06_display_handle()"
require_text docs/moui-integration-smoke.md "Window::rwh_06_window_handle()"
require_text docs/moui-integration-smoke.md "destroy requested"
require_text docs/moui-integration-smoke.md "--consumer-command \"scripts/check_moui_macos_smoke.sh --run\""
require_text docs/testing.md "execute the smoke through"
require_text docs/testing.md "moon run"
require_text docs/moui-integration-smoke.md "browser http://127.0.0.1:8000/examples/moui_web_smoke/index.html"
require_text docs/moui-integration-smoke.md "scripts/check_moui_runtime_log.sh linux <captured-log>"
require_text docs/moui-integration-smoke.md "scripts/check_moui_runtime_log.sh windows <captured-log>"
require_text docs/moui-integration-smoke.md 'nonzero `primary_id` and `current_id`'
require_text docs/moui-integration-smoke.md "nonzero Wayland/XDG handles"
require_text docs/moui-integration-smoke.md "--linux-input pending-ok"
require_text docs/moui-integration-smoke.md "positive surface size and scale"
require_text docs/moui-integration-smoke.md "positive monitor count"
require_text docs/moui-integration-smoke.md "delivered resize events after"
require_text docs/moui-integration-smoke.md 'keyboard text `a` before `ready`'
require_text docs/moui-integration-smoke.md 'pointer/keyboard/IME text `a` before `ready`'
require_text docs/moui-integration-smoke.md "raw display/window identity"
require_text docs/moui-integration-smoke.md "replays its captured transcript through"

require_text scripts/check_moui_web_smoke.sh "canvas_id=moui-web-smoke-canvas size=640x360"
require_text scripts/check_moui_web_smoke.sh "MOUISmoke: pointer x=24 y=32"
require_text scripts/check_moui_web_smoke.sh "MOUISmoke: keyboard text=a"
require_text scripts/check_web_assets.sh "wzzc-dev/window/examples/window_web/window_web.wasm"
require_text scripts/check_moui_web_smoke.sh "wzzc-dev/window/examples/moui_web_smoke/moui_web_smoke.wasm"
require_text scripts/check_web_assets.sh "moon --target-dir \"\$ROOT/_build\" build examples/window_web --target wasm-gc"
require_text scripts/check_moui_web_smoke.sh "moon --target-dir \"\$ROOT/_build\" build examples/moui_web_smoke --target wasm-gc"
require_text examples/moui_web_smoke/index.html "requiredEvidence"
require_text examples/moui_web_smoke/index.html "MOUISmoke: surface canvas_id=moui-web-smoke-canvas size=640x360"
require_text examples/moui_web_smoke/index.html "MOUISmoke: pointer x=24 y=32"
require_text examples/moui_web_smoke/index.html "MOUISmoke: keyboard text=a"
require_text examples/window_web/index.html "wzzc-dev/window/examples/window_web/window_web.wasm"
require_text examples/moui_web_smoke/index.html "wzzc-dev/window/examples/moui_web_smoke/moui_web_smoke.wasm"

require_text scripts/check_moui_macos_smoke.sh "window.available_monitors()"
require_text scripts/check_moui_macos_smoke.sh "window.current_monitor()"
require_text scripts/check_moui_macos_smoke.sh "window.set_cursor_icon(Text)"
require_text scripts/check_moui_macos_smoke.sh "moon run \"\$pkg\" --target native"
require_text examples/moui_macos_smoke/main.mbt "MOUIMacSmoke: monitors"
require_text examples/moui_macos_smoke/main.mbt "MOUIMacSmoke: cursor"

require_text scripts/check_moui_linux_smoke.sh "MoUI Linux core runtime smoke passed"
require_text scripts/check_moui_linux_smoke.sh "MoUI Linux runtime smoke passed"
require_text scripts/check_moui_linux_smoke.sh "--require-input"
require_text scripts/check_moui_linux_smoke.sh "WINDOW_MOUI_LINUX_REQUIRE_INPUT"
require_text scripts/check_moui_linux_smoke.sh "run_runtime_verifier"
require_text scripts/check_moui_linux_smoke.sh "window.available_monitors()"
require_text scripts/check_moui_linux_smoke.sh "window.current_monitor()"
require_text scripts/check_moui_linux_smoke.sh "window.set_cursor_icon(Text)"
require_text scripts/check_moui_runtime_log.sh "MOUILinuxSmoke: handles wl_display=0x"
require_text scripts/check_moui_runtime_log.sh "xdg_toplevel=0x"
require_text scripts/check_moui_runtime_log.sh "MOUILinuxSmoke: monitors count="
require_text scripts/check_moui_runtime_log.sh "primary_id=0x"
require_text scripts/check_moui_runtime_log.sh "current=true"
require_text scripts/check_moui_runtime_log.sh "current_id=0x"
require_text scripts/check_moui_runtime_log.sh "MOUILinuxSmoke: cursor Icon(Text)"
require_text scripts/check_moui_runtime_log.sh "MOUILinuxSmoke: ime probe enabled=true hint=true surrounding=true cursor=true updated=true updated_hint=true updated_cursor=true disabled=true"
require_text scripts/check_moui_linux_smoke.sh "scripts/check_moui_runtime_log.sh linux"
require_text scripts/check_moui_linux_smoke.sh "window.ime_hints()"
require_text scripts/check_moui_linux_smoke.sh "window.ime_purpose()"
require_text scripts/check_moui_linux_smoke.sh "updated_hint=\{updated_hint_ok}"
require_text linux/monitor.mbt "native_monitor_count"
require_text linux/monitor.mbt "current_monitor_for_window"
require_text linux/monitor_wbtest.mbt "does not fall back without surface output"
require_ordered_text linux/window.mbt "app_state_window_handle(self.raw_id())" "current_monitor_for_window(handle)"
require_text linux/monitor_wbtest.mbt "window.current_monitor() == None"
require_text linux/native_wayland.c "wl_output_add_listener"
require_text linux/native_wayland.c "mbw_wayland_window_current_monitor_handle"
require_text linux/native_wayland.c "destroy_window_resources(window)"
require_text linux/native_wayland.c "detach_window_from_context(window)"
require_text linux/native_wayland.c "flush_wayland_display"
require_text linux/native_wayland.c "MBW_WAYLAND_FLUSH_NEEDS_WRITE"
require_text linux/native_wayland.c "POLLOUT"
require_text linux/native_wayland.c "Wayland display fd error"
require_text linux/native_wayland.c "flush_wayland_display(context->display, \"window create\")"
require_text linux/native_wayland.c "flush_wayland_display(window->context->display, \"present\")"
require_text linux/native_wayland.c "unlink_present_buffer(frame)"
require_text linux/native_wayland.c "destroy_context_windows(context)"
require_text linux/native_wayland.c "context->windows = NULL"
require_text linux/native_wayland.c "context->wake_fd = -1"
require_text linux/native_wayland.c "if (context->wake_fd < 0)"
require_text linux/native_wayland.c "if (!context->registry)"
require_text linux/native_wayland.c "if (wl_display_roundtrip(context->display) < 0)"
require_text linux/native_wayland.c "!context->shm || !context->wm_base"
require_text linux/native_wayland.c "if (!context->seat)"
require_text linux/native_wayland.c "if (!context->wm_base)"
require_text linux/native_wayland.c "if (context->pointer)"
require_text linux/native_wayland.c "if (context->keyboard)"
require_ordered_text linux/native_wayland.c "wl_pointer_destroy(context->pointer);" "context->pointer_window = NULL;"
require_ordered_text linux/native_wayland.c "wl_keyboard_destroy(context->keyboard);" "context->keyboard_window = NULL;"
require_text linux/native_wayland.c "if (!window->xdg_surface)"
require_text linux/native_wayland.c "if (!window->xdg_toplevel)"
require_text linux/native_wayland.c "context->pointer_window == window"
require_text linux/native_wayland.c "context->keyboard_window == window"
require_text examples/moui_linux_smoke/main.mbt "MOUILinuxSmoke: ready input=pending"
require_text examples/moui_linux_smoke/main.mbt "MOUILinuxSmoke: ready input=observed"
require_text examples/moui_linux_smoke/main.mbt "window.request_ime_update(Enable(enable))"
require_text examples/moui_linux_smoke/main.mbt "window.request_ime_update(Update(update_data))"
require_text examples/moui_linux_smoke/main.mbt "window.request_ime_update(Disable)"
require_text examples/moui_linux_smoke/main.mbt "MOUILinuxSmoke: ime probe enabled="
require_text examples/moui_linux_smoke/main.mbt "hint=\{hint_ok}"
require_text examples/moui_linux_smoke/main.mbt "updated_hint=\{updated_hint_ok}"
require_text examples/moui_linux_smoke/main.mbt "window.ime_hints()"
require_text examples/moui_linux_smoke/main.mbt "window.ime_purpose()"
require_text linux/ime_wbtest.mbt "assert_eq(window.ime_purpose(), Url)"
require_text docs/testing.md "Linux and Windows IME request whitebox coverage"
require_text examples/moui_linux_smoke/main.mbt "key_event.text()"
require_text examples/moui_linux_smoke/main.mbt "MOUILinuxSmoke: keyboard text="
require_text examples/moui_linux_smoke/main.mbt "window.drop()"
require_text examples/moui_linux_smoke/main.mbt "MOUILinuxSmoke: destroy requested"
require_ordered_text linux/app_state.mbt "fn app_state_clear_window_runtime_state(raw_id : Int)" "app_state_clear_pending_redraw(raw_id)"
require_ordered_text linux/app_state.mbt "app_state_clear_pending_redraw(raw_id)" "app_state_unregister_window(raw_id)"
require_ordered_text linux/app_state.mbt "fn app_state_queue_redraw(raw_id : Int)" "app_state_window_handle(raw_id)"
require_ordered_text linux/app_state.mbt "app_state_window_handle(raw_id)" "pending_redraw_window_ids.push(raw_id)"
require_ordered_text linux/event.mbt "app_state_clear_modifiers()" "app_state_clear_window_runtime_state(raw_id)"
require_ordered_text linux/event.mbt "app_state_clear_window_runtime_state(raw_id)" "app_state_queue_window_event(raw_id, Destroyed)"
require_ordered_text linux/window.mbt "native_window_destroy(self.handle)" "app_state_clear_window_runtime_state(self.raw_id())"
require_text linux/event_wbtest.mbt "app_state_window_handle(raw_id) == None"
require_text linux/event_wbtest.mbt "pending_redraw_window_ids.length(), 0"
require_text linux/event_wbtest.mbt "linux window runtime cleanup clears app state handle and redraws"
require_text linux/event_wbtest.mbt "linux redraw queue ignores unregistered windows"
require_text examples/moui_linux_smoke/main.mbt "MOUILinuxSmoke: monitors"
require_text examples/moui_linux_smoke/main.mbt "monitor.native_id()"
require_text examples/moui_linux_smoke/main.mbt "self.saw_monitor = log_monitor_probe(window)"
require_text examples/moui_linux_smoke/main.mbt "self.saw_cursor = log_cursor_probe(window)"
require_text examples/moui_linux_smoke/main.mbt "cursor=\{self.saw_cursor}"
require_text examples/moui_linux_smoke/main.mbt "primary_id=0x"
require_text examples/moui_linux_smoke/main.mbt "current_id=0x"
require_text examples/moui_linux_smoke/main.mbt "MOUILinuxSmoke: cursor"
require_text examples/moui_linux_smoke/main.mbt "event_loop.set_control_flow(Wait)"
require_text examples/moui_linux_smoke/main.mbt "Destroyed"
require_text docs/testing.md "Linux event bridge whitebox tests"
require_text docs/testing.md "Wayland configure normalization"
require_text linux/event_wbtest.mbt "linux dispatch maps pointer enter leave button release and wheel"
require_text linux/event_wbtest.mbt "linux dispatch normalizes empty configure sizes"
require_text linux/event_wbtest.mbt "linux dispatch tracks modifier release by key family"
require_text linux/event_wbtest.mbt "linux dispatch ignores invalid raw ids except proxy wake"
require_text linux/event.mbt "raw_id <= 0 || app_state_window_handle(raw_id) is None"
require_text linux/event_wbtest.mbt "linux input dispatch ignores unregistered windows"
require_text linux/event_wbtest.mbt "linux window dispatch ignores unregistered windows"
require_text linux/app_state.mbt "app_state_clear_context_windows"
require_text linux/app_state.mbt "app_state_runtime.val.window_entries = []"
require_text linux/app_state.mbt "app_state_runtime.val.pending_redraw_window_ids = []"
require_text linux/event_wbtest.mbt "linux event loop drop cleanup clears app state context windows and redraws"
require_text linux/event_wbtest.mbt "app_state_window_handle(raw_id) == None"
require_text linux/event_wbtest.mbt "pending_redraw_window_ids.length(), 0"
require_ordered_text linux/event_loop.mbt "native_context_destroy(self.context)" "app_state_clear_context_windows(self.context)"
require_text docs/testing.md "invalid raw-id filtering"
require_text docs/testing.md "Linux input-dispatch whitebox coverage requires an app-state live window handle"
require_text docs/testing.md "Linux window-dispatch whitebox coverage likewise requires an app-state live"
require_text docs/testing.md "clears the stored Wayland context handle"
require_text docs/testing.md "Wayland flush failures"
require_text docs/testing.md "write-ready polling"

require_text scripts/check_moui_macos_smoke.sh "require_output_order"
require_text scripts/check_moui_windows_smoke.sh "run_runtime_verifier"
require_text scripts/check_moui_windows_smoke.sh "window.available_monitors()"
require_text scripts/check_moui_windows_smoke.sh "window.current_monitor()"
require_text scripts/check_moui_windows_smoke.sh "window.set_cursor_icon(Text)"
require_text scripts/check_moui_runtime_log.sh "MOUIWindowsSmoke: handle hwnd=0x"
require_text scripts/check_moui_runtime_log.sh "hinstance=0x"
require_text scripts/check_moui_runtime_log.sh "raw_display=0x"
require_text scripts/check_moui_runtime_log.sh "raw_window=0x"
require_text scripts/check_moui_runtime_log.sh "MOUIWindowsSmoke: monitors count="
require_text scripts/check_moui_runtime_log.sh "primary_id=0x"
require_text scripts/check_moui_runtime_log.sh "current=true"
require_text scripts/check_moui_runtime_log.sh "current_id=0x"
require_text scripts/check_moui_runtime_log.sh "MOUIWindowsSmoke: cursor Icon(Text)"
require_text scripts/check_moui_windows_smoke.sh "scripts/check_moui_runtime_log.sh windows"
require_text examples/moui_windows_smoke/main.mbt "self.saw_monitor = log_monitor_probe(window)"
require_text examples/moui_windows_smoke/main.mbt "window.display_handle()"
require_text examples/moui_windows_smoke/main.mbt "window.rwh_06_display_handle()"
require_text examples/moui_windows_smoke/main.mbt "window.rwh_06_window_handle()"
require_text examples/moui_windows_smoke/main.mbt "display != (0 : Int).to_uint64()"
require_text examples/moui_windows_smoke/main.mbt "raw_display == display"
require_text examples/moui_windows_smoke/main.mbt "raw_window == hwnd"
require_text scripts/check_moui_windows_smoke.sh "window.request_ime_update(Enable(enable))"
require_text scripts/check_moui_windows_smoke.sh "window.request_ime_update(Update(update_data))"
require_text scripts/check_moui_windows_smoke.sh "window.request_ime_update(Disable)"
require_text examples/moui_windows_smoke/main.mbt "Ime(Commit(text))"
require_text examples/moui_windows_smoke/main.mbt "MOUIWindowsSmoke: keyboard key="
require_text examples/moui_windows_smoke/main.mbt "MOUIWindowsSmoke: ime probe enabled="
require_text examples/moui_windows_smoke/main.mbt "hint=\{hint_ok}"
require_text examples/moui_windows_smoke/main.mbt "updated_hint=\{updated_hint_ok}"
require_text examples/moui_windows_smoke/main.mbt "window.ime_hints()"
require_text examples/moui_windows_smoke/main.mbt "window.ime_purpose()"
require_text windows/window.mbt "ime_hints_state"
require_text windows/window.mbt "ime_purpose_state"
require_text windows/ime_wbtest.mbt "assert_eq(window.ime_purpose(), Url)"
require_text examples/moui_windows_smoke/main.mbt "window.drop()"
require_text examples/moui_windows_smoke/main.mbt "MOUIWindowsSmoke: destroy requested"
require_ordered_text windows/app_state.mbt "fn app_state_clear_window_runtime_state(raw_id : Int)" "clear_windows_window_input_state(raw_id)"
require_ordered_text windows/app_state.mbt "clear_windows_window_input_state(raw_id)" "app_state_clear_pending_redraw(raw_id)"
require_ordered_text windows/app_state.mbt "app_state_clear_pending_redraw(raw_id)" "app_state_unregister_window_handle(raw_id)"
require_ordered_text windows/app_state.mbt "fn app_state_queue_redraw(raw_id : Int)" "app_state_window_handle(raw_id)"
require_ordered_text windows/app_state.mbt "app_state_window_handle(raw_id)" "pending_redraw_window_ids.push(raw_id)"
require_ordered_text windows/event.mbt "app_state_clear_window_runtime_state(raw_id)" "app_state_queue_window_event(raw_id, Destroyed)"
require_ordered_text windows/window.mbt "native_destroy_window(self.hwnd)" "app_state_clear_window_runtime_state(self.id.into_raw())"
require_text windows/event_wbtest.mbt "app_state_window_handle(raw_id) == None"
require_text windows/event_wbtest.mbt "pending_redraw_window_ids.length(), 0"
require_text windows/event_wbtest.mbt "windows window runtime cleanup clears input handle and redraws"
require_text windows/event_wbtest.mbt "windows redraw queue ignores unregistered windows"
require_text examples/moui_windows_smoke/main.mbt "MOUIWindowsSmoke: monitors"
require_text examples/moui_windows_smoke/main.mbt "monitor.native_id()"
require_text examples/moui_windows_smoke/main.mbt "self.saw_cursor = log_cursor_probe(window)"
require_text examples/moui_windows_smoke/main.mbt "cursor=\{self.saw_cursor}"
require_text examples/moui_windows_smoke/main.mbt "primary_id=0x"
require_text examples/moui_windows_smoke/main.mbt "current_id=0x"
require_text examples/moui_windows_smoke/main.mbt "MOUIWindowsSmoke: cursor"
require_text examples/moui_windows_smoke/input_native.c "WM_CHAR"
require_text examples/moui_windows_smoke/main.mbt "Destroyed"
require_text docs/testing.md "Windows event bridge whitebox tests"
require_text windows/native_window.c "suggested_width"
require_text windows/native_window.c "suggested_height"
require_text windows/event.mbt "text_from_windows_char_code"
require_text windows/event_wbtest.mbt "windows dispatch maps resize scale pointer keyboard ime and redraw"
require_text windows/event_wbtest.mbt "windows dispatch ignores invalid wm char code units"
require_text windows/event_wbtest.mbt "windows dispatch ignores invalid raw ids"
require_text windows/event.mbt "raw_id <= 0 || app_state_window_handle(raw_id) is None"
require_text windows/event_wbtest.mbt "windows input dispatch ignores unregistered windows"
require_text windows/event_wbtest.mbt "windows window dispatch ignores unregistered windows"
require_text windows/event_wbtest.mbt "PhysicalSize(400, 240)"
require_text windows/event_wbtest.mbt "sync query requires a registered window handle"
require_text windows/native_monitor.c "if (!IsWindow(window)) return 0;"
require_ordered_text windows/window.mbt "app_state_window_handle(self.id.into_raw())" "current_monitor_for_window(hwnd)"
require_text windows/monitor_wbtest.mbt "window.current_monitor() == None"
require_text windows/monitor_wbtest.mbt "windows current monitor rejects invalid hwnd handles"
require_text windows/event_loop.mbt "native_destroy_window(self.msg_window)"
require_text windows/app_state.mbt "app_state_clear_all_window_runtime_state"
require_text windows/app_state.mbt "app_state_runtime.val.window_handles = []"
require_text windows/app_state.mbt "app_state_runtime.val.pending_redraw_window_ids = []"
require_ordered_text windows/event_loop.mbt "native_destroy_window(self.msg_window)" "app_state_clear_all_window_runtime_state()"
require_text windows/event_wbtest.mbt "windows event loop drop cleanup clears app state windows input and redraws"
require_text windows/event_loop.mbt "if msg_window == (0 : Int).to_uint64()"
require_text windows/native_window.c "window == g_msg_window"
require_text windows/native_window.c "g_msg_window = NULL"
require_text windows/native_window.c "g_main_thread_id = 0"
require_text windows/native_window.c "mbw_publish_window_state"
require_text windows/native_window.c "mbw_clear_window_state(hwnd)"
require_text windows/native_window.c "state->raw_id != raw_id"
require_text windows/native_window.c "DestroyWindow(hwnd)"
require_text windows/native_window.c "FreeLibrary(imm32)"
require_text windows/native_window.c "g_imm_get_composition_string = NULL"
require_text docs/testing.md "missing raw-id state, and message-window destroy clear"
require_text docs/testing.md "clears loop-owned app-state HWNDs"
require_text docs/testing.md "partial loads are released and cleared"
require_text docs/testing.md "invalid raw-id filtering"
require_text docs/testing.md "Windows input-dispatch whitebox coverage requires an app-state live HWND"
require_text docs/testing.md "Windows window-dispatch whitebox coverage likewise requires an app-state live"
require_text docs/testing.md "Windows monitor whitebox tests"
require_text windows/native_window.c "if (!new_state)"
require_text windows/native_window.c "return FALSE;"
require_text windows/native_window.c "cs->lpCreateParams"
require_text windows/native_window.c "(LPVOID)(intptr_t)raw_id"
require_text windows/window.mbt "parent_hwnd, raw_id"
require_ordered_text windows/window.mbt "app_state_register_window_handle(raw_id, hwnd)" "native_set_window_raw_id(hwnd, raw_id)"
require_ordered_text windows/window.mbt "app_state_register_window_handle(raw_id, hwnd)" "native_show_window(hwnd, sw_shownormal)"
require_text windows/monitor.mbt "windows_monitor_surface_size"
require_text windows/monitor.mbt "windows_monitor_scale_factor"
require_text windows/native_monitor.c "mbw_clear_monitor_cache"
require_text windows/native_monitor.c "state.failed"
require_text windows/native_monitor.c "EnumDisplayMonitors("
require_text windows/native_monitor.c "SUCCEEDED(hr) && dpi_x > 0"
require_text windows/native_monitor.c "utf8_len <= 0"
require_text windows/native_monitor.c "written != utf8_len"
require_text windows/native_monitor.c "return 0;"
require_text docs/testing.md "monitor name conversion returns an empty name"
require_text windows/window.mbt "windows_scale_factor_from_dpi"
require_text windows/monitor_wbtest.mbt "windows monitor helpers normalize invalid size and scale"
require_text windows/monitor_wbtest.mbt "windows dpi scale helper falls back for zero dpi"
reject_text windows/window.mbt "scale_factor_state"

require_text scripts/smoke_runtime.sh "Automated Linux MoUI strict smoke"
require_text scripts/smoke_runtime.sh "env WINDOW_MOUI_LINUX_REQUIRE_INPUT=1 scripts/check_moui_linux_smoke.sh --run"
require_text scripts/smoke_runtime.sh "Automated Windows MoUI smoke"
require_text scripts/smoke_runtime.sh "scripts/check_moui_web_smoke.sh"
require_text scripts/smoke_runtime.sh "examples/moui_web_smoke/index.html for MoUI consumer evidence"
require_text scripts/check_runtime_smoke.sh "expect_log_success linux"
require_text scripts/check_runtime_smoke.sh "expect_log_failure windows"
require_text scripts/check_runtime_smoke.sh "expect_log_order_failure"
require_text scripts/check_moui_runtime_log.sh "require_current_monitor_id"
require_text scripts/check_moui_runtime_log.sh 'require_nonzero_hex "$prefix current_id"'
require_text scripts/check_moui_runtime_log.sh "extract_token_field"
require_text scripts/check_moui_runtime_log.sh "duplicate field"
require_text scripts/check_moui_runtime_log.sh "field size must be WIDTHxHEIGHT"
require_text scripts/check_moui_runtime_log.sh "require_surface_probe"
require_text scripts/check_moui_runtime_log.sh "require_resize_delivery"
require_text scripts/check_moui_runtime_log.sh "require_pointer_probe"
require_text scripts/check_moui_runtime_log.sh "require_single_matching_line"
require_text scripts/check_moui_runtime_log.sh "require_single_prefixed_line"
require_text scripts/check_moui_runtime_log.sh "require_single_exact_line"
require_text scripts/check_moui_runtime_log.sh "require_exact_output_order"
require_text scripts/check_moui_runtime_log.sh "require_last_prefixed_line"
require_text scripts/check_moui_runtime_log.sh "require_ready_after_evidence"
require_text scripts/check_moui_runtime_log.sh "require_positive_size_line"
require_text scripts/check_moui_runtime_log.sh "require_positive_decimal"
require_text scripts/check_moui_runtime_log.sh "MOUILinuxSmoke wl_display"
require_text scripts/check_moui_runtime_log.sh "MOUILinuxSmoke xdg_toplevel"
require_text scripts/check_moui_runtime_log.sh "linux_input_mode"
require_text scripts/check_moui_runtime_log.sh "raw_display identity"
require_text scripts/check_moui_runtime_log.sh "MOUILinuxSmoke: keyboard text=a"
require_text scripts/check_moui_runtime_log.sh "MOUIWindowsSmoke: ime text=a"
require_text scripts/check_moui_runtime_log.sh "MOUIWindowsSmoke: keyboard key=a"
require_text scripts/check_moui_runtime_log.sh "MOUIWindowsSmoke: ime probe enabled=true hint=true surrounding=true cursor=true updated=true updated_hint=true updated_cursor=true disabled=true"
require_text scripts/check_moui_runtime_log.sh "reject_prefixed_failure_lines"
require_text scripts/check_moui_runtime_log.sh 'reject_output "$output" "MOUIWindowsSmoke:"'
require_text scripts/check_moui_runtime_log.sh 'reject_output "$output" "MOUILinuxSmoke:"'
require_text scripts/check_runtime_smoke.sh "expect_log_appended_failure"
require_text scripts/check_runtime_smoke.sh "expect_log_appended_line_failure"
require_text scripts/check_runtime_smoke.sh "expect_log_move_after_failure"
require_text scripts/check_runtime_smoke.sh "exactly one line with"
require_text scripts/check_runtime_smoke.sh "MOUILinuxSmoke: finished, got 2"
require_text scripts/check_runtime_smoke.sh "MOUIWindowsSmoke: destroyed, got 2"
require_text scripts/check_runtime_smoke.sh "MOUILinuxSmoke: monitors count=, got 2"
require_text scripts/check_runtime_smoke.sh "MOUIWindowsSmoke: handle hwnd=0x, got 2"
require_text scripts/check_runtime_smoke.sh "resize request width must be positive"
require_text scripts/check_runtime_smoke.sh "resize request height must be positive"
require_text scripts/check_runtime_smoke.sh "last MOUILinuxSmoke line must be MOUILinuxSmoke: finished"
require_text scripts/check_runtime_smoke.sh "last MOUIWindowsSmoke line must be MOUIWindowsSmoke: finished"
require_text scripts/check_runtime_smoke.sh "missing field x"
require_text scripts/check_runtime_smoke.sh "field x must be an integer"
require_text scripts/check_runtime_smoke.sh "field size must be WIDTHxHEIGHT"
require_text scripts/check_runtime_smoke.sh "duplicate field raw_window"
require_text scripts/check_runtime_smoke.sh "MOUIWindowsSmoke: keyboard key=b"
require_text scripts/check_runtime_smoke.sh "note MOUILinuxSmoke: present result=0"
require_text scripts/check_runtime_smoke.sh "note MOUIWindowsSmoke: handle hwnd=0x111"
require_text scripts/check_runtime_smoke.sh "MOUILinuxSmoke: destroyed later"
require_text scripts/check_runtime_smoke.sh "MOUIWindowsSmoke: readyish"
require_text scripts/check_runtime_smoke.sh "MOUILinuxSmoke: keyboard text=ab"
require_text scripts/check_runtime_smoke.sh "MOUIWindowsSmoke: keyboard key=ab"
require_text scripts/check_runtime_smoke.sh "MOUIWindowsSmoke: ime text=ab"
require_text scripts/check_runtime_smoke.sh "log contained forbidden text: MOUIWindowsSmoke:"
require_text scripts/check_runtime_smoke.sh "log contained forbidden text: MOUILinuxSmoke:"
require_text scripts/check_runtime_smoke.sh "input=observed"
require_text docs/testing.md "input-before-ready failures"
require_text docs/testing.md "core-evidence-before-ready failures"
require_text docs/testing.md "non-prefixed smoke evidence rejection"
require_text docs/testing.md "duplicate startup-probe failures"
require_text docs/testing.md "invalid resize-request failures"
require_text docs/testing.md "unique startup probes"
require_text docs/testing.md "positive resize request sizes"
require_text docs/testing.md "Ready and teardown"
require_text docs/testing.md "near-miss values such"
require_text docs/testing.md "duplicate-ready sentinel failures"
require_text docs/testing.md "duplicate-teardown sentinel failures"
require_text docs/testing.md "post-finished smoke-line failures"
require_text docs/testing.md "prefixed smoke failure-line rejection"
require_text docs/testing.md "pointer coordinate-field failures"
require_text docs/platform-gaps.md "scripts/check_moui_runtime_log.sh linux <captured-log>"
require_text docs/platform-gaps.md "scripts/check_moui_runtime_log.sh windows <captured-log>"
require_text docs/platform-gaps.md "--linux-input pending-ok"
require_text docs/platform-gaps.md "positive surface size/scale"
require_text docs/platform-gaps.md "positive monitor count"
require_text docs/platform-gaps.md "unique startup probes"
require_text docs/platform-gaps.md "positive resize request sizes"
require_text docs/platform-gaps.md "delivered resize events after"
require_text docs/platform-gaps.md 'input/text/IME before `ready`'
require_text scripts/check_moui_linux_smoke.sh "bash scripts/check_moui_runtime_log.sh"
require_text scripts/check_moui_linux_smoke.sh "--linux-input pending-ok"
require_text scripts/check_moui_windows_smoke.sh "bash scripts/check_moui_runtime_log.sh"
require_text scripts/record_moui_evidence.sh "prints to stdout only"
require_text scripts/record_moui_evidence.sh "native-backend evidence must be generated on the matching host"
require_text scripts/record_moui_evidence.sh "Use --host to name the remote matching host"
require_text scripts/record_moui_evidence.sh 'requires explicit `yes` values'
require_text scripts/record_moui_evidence.sh "--runtime-log"
require_text scripts/record_moui_evidence.sh "--runtime-log-command"
require_text scripts/record_moui_evidence.sh "Linux/Windows passed evidence requires"
require_text scripts/capture_moui_runtime_evidence.sh "bash scripts/record_moui_evidence.sh"
require_text scripts/capture_moui_runtime_evidence.sh "scripts/check_moui_runtime_log.sh"
require_text scripts/capture_moui_runtime_evidence.sh 'WINDOW_CI_HOST=$backend'
require_text scripts/capture_moui_runtime_evidence.sh "runtime evidence capture requires a"
require_text scripts/capture_moui_runtime_evidence.sh "before ready"
require_text scripts/capture_moui_runtime_evidence.sh "--log must name a concrete captured transcript path"
require_text scripts/capture_moui_runtime_evidence.sh "--log path cannot contain shell syntax"
require_text scripts/record_moui_evidence.sh "remote passed"
require_text scripts/record_moui_evidence.sh "--consumer-input"
require_text scripts/record_moui_evidence.sh "--text-input"
require_text scripts/record_moui_evidence.sh "--monitor-cursor"
require_text scripts/record_moui_evidence.sh "consumer evidence fields require --consumer-command"
require_text scripts/record_moui_evidence.sh "computed MoUI consumer status"
require_text scripts/record_moui_evidence.sh "consumer_status"
require_text scripts/record_moui_evidence.sh "change backend status"
require_text scripts/record_moui_evidence.sh "expected_runtime_log_command"
require_text scripts/record_moui_evidence.sh "runtime_log_command_has_shell_syntax"
require_text scripts/record_moui_evidence.sh "runtime_log_path_token_is_concrete"
require_text scripts/record_moui_evidence.sh "without --linux-input pending-ok"
require_text scripts/check_moui_evidence.sh "documented Web recorder template"
require_text scripts/check_moui_evidence.sh "documented Linux pending recorder template"
require_text scripts/check_moui_evidence.sh "documented Windows pending recorder template"
require_text scripts/check_moui_evidence.sh "hint/purpose enable/update probes"
require_text scripts/check_moui_evidence.sh "matching-host passed native evidence requires runtime log"
require_text scripts/check_moui_evidence.sh "remote passed evidence requires runtime log"
require_text scripts/check_moui_evidence.sh "runtime log command must run verifier"
require_text scripts/check_moui_evidence.sh "runtime log command must invoke verifier"
require_text scripts/check_moui_evidence.sh "runtime log command rejects shell suffix"
require_text scripts/check_moui_evidence.sh "runtime log command rejects extra args"
require_text scripts/check_moui_evidence.sh "runtime log command rejects placeholder path"
require_text scripts/check_moui_evidence.sh "runtime log command rejects variable path"
require_text scripts/check_moui_evidence.sh "passed linux evidence rejects pending-ok verifier"
require_text scripts/check_moui_evidence.sh "Runtime log: verified=pending"
require_text scripts/check_moui_evidence.sh "native monitor cursor pending keeps consumer pending"
require_text scripts/check_moui_evidence.sh "capture rejects placeholder log path"
require_text scripts/check_moui_evidence.sh "capture rejects shell log path"
require_text docs/testing.md "Smoke Matrix"
require_text docs/testing.md "computed MoUI consumer status"
require_text docs/testing.md "verifier command itself"
require_text docs/testing.md "concrete captured-log path"
require_text docs/testing.md "rejects transcripts that contain the other native"
require_text docs/testing.md "--runtime-log yes"
require_text docs/testing.md "--runtime-log-command"
require_text docs/testing.md "passed Linux/Windows evidence"
require_text docs/testing.md "Linux/Windows evidence"
require_text docs/testing.md "surface enter/current-output tracking"
require_text docs/testing.md "bash scripts/record_moui_evidence.sh <backend>"
require_text docs/testing.md "--host \"Linux Weston CI\""
require_text docs/platform-gaps.md "public IME state probes"
require_text docs/platform-gaps.md "Wayland IME/preedit delivery"
require_text docs/platform-gaps.md 'Wayland `wl_output` monitor/current-monitor probes'
require_text docs/platform-gaps.md "surface enter/current-output tracking"
require_text docs/platform-gaps.md "HWND/HINSTANCE/raw-display handle fields"
require_text docs/platform-gaps.md "raw display/window identity"
require_text docs/platform-gaps.md "HINSTANCE-backed display handles"
require_text docs/platform-gaps.md "bash scripts/record_moui_evidence.sh <backend>"
require_text docs/platform-gaps.md "status=<passed/failed/pending>"
require_text docs/platform-gaps.md "computed MoUI consumer status"
require_text docs/platform-gaps.md "Runtime log: verified=<yes/no/pending>"
require_text docs/platform-gaps.md "--runtime-log yes"
require_text docs/platform-gaps.md "--runtime-log-command"
require_text docs/platform-gaps.md "the verifier command itself"
require_text docs/platform-gaps.md "scripts/check_ffi_surface.sh"
require_text docs/platform-gaps.md 'pass `--host` with the'
require_text docs/platform-gaps.md 'matching host description so the entry cannot be confused with local smoke'
require_text scripts/check_ffi_surface.sh "ffi-linux-export-allowlist.txt"
require_text scripts/check_ffi_surface.sh "ffi-windows-export-allowlist.txt"
require_text scripts/check_ffi_surface.sh "check_binding_exports \"Linux\""
require_text scripts/check_ffi_surface.sh "check_binding_exports \"Windows\""
require_text scripts/check_ffi_surface.sh "check_branch_exports \"Linux\""
require_text scripts/check_ffi_surface.sh "check_branch_exports \"Windows\""
require_text scripts/check_ffi_surface.sh "check_branch_signatures \"Linux\""
require_text scripts/check_ffi_surface.sh "check_branch_signatures \"Windows\""
require_text docs/ffi-linux-export-allowlist.txt "mbw_wayland_monitor_count"
require_text docs/ffi-linux-export-allowlist.txt "mbw_wayland_window_current_monitor_handle"
require_text docs/ffi-windows-export-allowlist.txt "mbw_hinstance_handle"
require_text docs/ffi-windows-export-allowlist.txt "mbw_current_monitor_handle"
require_text README.mbt.md "docs/moui-integration-smoke.md"
require_text README.mbt.md "bash scripts/record_moui_evidence.sh"
require_text README.mbt.md "--runtime-log yes"
require_text README.mbt.md "--runtime-log-command"

printf 'MoUI readiness check passed\n'
